apiVersion: v1
kind: Pod
metadata:
   name: comments-consumer
spec:
   containers:
   - name: youtube-comment-consumer
     image: consumer:latest
     imagePullPolicy: Never
     env:
    - name: MINIO_HOME
      valueFrom:
        secretKeyRef:
          name: miniocredentials
          key: miniohome
    - name: MINIO_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: miniocredentials
          key: accesskey
    - name: MINIO_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: miniocredentials
          key: secretkey