apiVersion: v1
kind: Pod
metadata:
   name: minio
spec:
   containers:
   - name: minio
     image: quay.io/minio/minio:latest
     command:
     - /bin/bash
     - -c
     args: 
     - minio server /data --console-address :9090