apiVersion: compute.functionmesh.io/v1alpha1
kind: Function
metadata:
  name: python-csv-writter
  namespace: default
spec:
  image: cloud-sink:latest # using function image here
  imagePullPolicy: Never
  className: sink-csv.SinkCSV
  forwardSourceMessageProperty: true
  maxPendingAsyncRequests: 1000
  replicas: 1
  maxReplicas: 5
  logTopic: persistent://public/default/logging-function-logs
  input:
    topics:
      - persistent://public/default/complete-youtube
    typeClassName: java.lang.String
  resources:
    requests:
      cpu: "0.1"
      memory: 1G
    limits:
      cpu: "0.2"
      memory: 1.1G
  pulsar:
    pulsarConfig: 'test-pulsar-sink'
  python:
    py: /pulsar/sink-csv.py
    pyLocation: ''

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-pulsar-sink
  namespace: default
data:
  webServiceURL: http://192.168.49.2:32311/
  brokerServiceURL: pulsar://192.168.49.2:31482/
  MINIO_HOME: 
  MINIO_ACCESS_KEY: 
  MINIO_SECRET_KEY: 
---