apiVersion: compute.functionmesh.io/v1alpha1
kind: Function
metadata:
  name: python-hatespeechdetector
  namespace: default
spec:
  image: hatespeech:latest # using function image here
  imagePullPolicy: Never
  className: hate_speech_detector.HateSpeechDetector
  forwardSourceMessageProperty: true
  maxPendingAsyncRequests: 1000
  replicas: 1
  maxReplicas: 5
  logTopic: persistent://public/default/logging-function-logs
  input:
    topics:
      - persistent://public/default/liked-comments
      - persistent://public/default/common-ita-words
    typeClassName: java.lang.String
  output:
    topic: persistent://public/default/hate
    typeClassName: java.lang.String
  resources:
    requests:
      cpu: "0.1"
      memory: 1G
    limits:
      cpu: "0.2"
      memory: 1.1G
  pulsar:
    pulsarConfig: 'test-pulsar-hs'
  python:
    py: /pulsar/hate_speech_detector.py
    pyLocation: ''

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-pulsar-hs
  namespace: default
data:
  webServiceURL: http://192.168.49.2:31423/
  brokerServiceURL: pulsar://192.168.49.2:31640/
---