apiVersion: v1
kind: Pod
metadata:
   name: youtube-collector
spec:
   containers:
   - name: youtube-comment-collector-italy
     image: collector:latest
     imagePullPolicy: Never
     env:
     - name: YOUTUBE_API_KEY
       value: ""